### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by furkansenharputlu** [furkansenharputlu/f-license#1]
Licenses should be saved to DB. So generator also needs storage.

### License Server API
- [x]  Generate
- [ ]  Update
- [x]  Delete
- [x]  Get
- [x]  Verify
- [x]  Activate
- [x]  Inactivate

###  Client code on different languages
- [x] Go
- [ ] Java
- [ ] Javascript
- [ ] Python

### Verification
- [x] Remote Verification with SSL/TLS
- [x] Local verification

### Authentication Algorithms
- [x] HMAC
- [x] RSA

### CLI
- [x]  Generate
- [ ]  Update
- [x]  Delete
- [x]  Get
- [x]  Verify
- [x]  Activate
- [x]  Inactivate

### Other open source features
- [ ] License Versioning
- [ ] IP whitelisting/blacklisting
- [ ] Analytics

### Dashboard should provide:
- [ ] Customer management
- [ ] JWT playground
- [ ] Customer portal to create trial license
- [ ] Email notifications(generated, expire date is closing, expired, activated, inactivated)
- [ ] Analytics visualization
- [ ] Customers can specify their license. For example, they can enhance it by a payload including version info etc. 
- [ ] Auto client code generation

**Comment by rread** [comment]
Here's one vote for a Swift client.
